---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
generator:
  name: "NewSpringBootRestService"
  group: "atomist"
  artifact: "spring-rugs"
  version: "0.13.3"
  parameters:
    - "artifactId": "myartifact"
    - "groupId": "mygroup"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "my new project"
    - "rootPackage": "com.myorg"
    - "serviceClassName": "Test"

---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170728065612"
editor:
  name: "AddAtomistAgent"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.7.9"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "4048638c0f9941d771fbd8436204148b144ff3e5"
    sha: "4048638"
  parameters:
    - "slackTeam": "T6HKM3XM0"

